### ISSUE TITLE
Resize the Font

### ISSUE THREAD

**Issue by Giza** [marcussacana/AquaPlusEditor#2]
Can you upload a patch or exe file. In my system,  cannot change the instructions.

Thanks.

**Comment by marcussacana** [comment]
[Utawarerumono Mask of Deception [Font Resize] [v2 Steam].7z](https://github.com/marcussacana/AquaPlusEditor/files/8832790/Utawarerumono.Mask.of.Deception.Font.Resize.v2.Steam.7z.zip)
If after you use this executable the game UI became broken, this mean your version of the game isn't the same of my version.

**Comment by Giza** [comment]
Thx
