### ISSUE TITLE
Any instuctions for non porgrammer dumbs?

### ISSUE THREAD

**Issue by Real-Lolypops** [marcussacana/AquaPlusEditor#3]
Hi,

I'm not a programmer and can't understand how to use this program. I open exe file, drop sdat file into, but console just closes. I tried to drop sdat on exe, but nothing seems to happen either. Am I doing it wrong? Is there anything else I need to know to decompile sdat files?

**Comment by marcussacana** [comment]
https://github.com/marcussacana/AquaPlusEditor/releases/download/1.0.69/APEGUI.zip

From this build, right click in the window, unpack the sdat and use open/save to edit the .bin file.

**Comment by Real-Lolypops** [comment]
How do I unpack sdat?

**Comment by Real-Lolypops** [comment]
Well, I did something. When I click pak - extract, choose sdat file, it creates bin files. After I click open - assert and choose bin file, the program demands on another bin file. It dosn't matter which one I choose, it ends with error or simply nothing. 

Tex files decrypt fine

**Comment by marcussacana** [comment]
there are script and database .bin files, you must open using the correct option.

**Comment by Real-Lolypops** [comment]
I honestly do not understand what do you mean. Which option is the correct option? You got one option in "open" option. 
![изображение](https://user-images.githubusercontent.com/65752329/212565906-0e622a86-4516-49cf-b003-d008c23e7bee.png)

**Comment by marcussacana** [comment]
Don't use the assert, click in the open

**Comment by Real-Lolypops** [comment]
Thanks for the instruction, I finally did something.

So I unpacked the whole Utawarerumono: Prelude to the Fallen (2021 remake) and some files of Itsuwari no Kamen. APE works fine with Itsuwari no Kamen and probably will work with third, as well. But I got like 90% of Prelude to the Fallen. Looks like some Hakuoro, Eruru and Aruru lines from the very start to the Hakuoro's recovery are missing. They just don't exist. And few bin files are empty.

For example, the very first Itsuwari no Kamen line named 11_01_000S,bin. The first line of Prelude to the Fallen named _00_00_02.bin. One might think, that the first line of Prelude to the Fallen would have named _00_00_01.bin, but it hasn't. Moreover, _00_00_02.bin of the first game doesn't have starting dialogues.

For some reasone ScriptEvents.dat in the ENG folder has only japanese language with some random latin letters or weird symbols. Bin files with weird symbols probably should have contained japanese alphabet characters. There are also fragments of phrases, like some of lines were corrupted due to decoding; empty bins. 

![изображение](https://user-images.githubusercontent.com/65752329/212573734-3558e409-e52b-47f3-a35a-1c7801152104.png)

It also impossible to change font language from latin to cyrillic, although conlolas font does support cyrillic alphabet. NullException error.

What would you recommend to fix these issues, and is there any chance you could test APE with Utawarerumono: Prelude to the Fallen?

**Comment by marcussacana** [comment]
I can't say anything from the error, there are no enough details.

**Comment by Real-Lolypops** [comment]
I click Fnt in APE, open Font.fnt in game data folder. As I mentioned before, I need this Consolant font the game uses to support cyrillic alphabet, which it does support. It's a default win font, I can type cyrillic with that. So I just add cyrillic characters to the "chars" line and save it. After I open the newly created Font.fnt file, the issue pops up:

See the end of this message for details on invoking just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at AquaPlusEditor.FNT.GetGlyphs() в C:\Program Files (x86)\Steam\steamapps\common\Utawarerumono - Mask of Deception\Data\APEGUI\AquaPlusEditor-master\AquaPlusEditor\FNT.cs:line 76
   at APEGUI.Form2.button1_Click(Object sender, EventArgs e) в C:\Program Files (x86)\Steam\steamapps\common\Utawarerumono - Mask of Deception\Data\APEGUI\AquaPlusEditor-master\APEGUI\Form2.cs:line 31
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
APEGUI
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/%D0%9D%D0%BE%D0%B2%D0%B0%D1%8F%20%D0%BF%D0%B0%D0%BF%D0%BA%D0%B0/APEGUI.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4590.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
AquaPlusEditor
    Assembly Version: 1.0.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/%D0%9D%D0%BE%D0%B2%D0%B0%D1%8F%20%D0%BF%D0%B0%D0%BF%D0%BA%D0%B0/AquaPlusEditor.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Core.resources
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Core.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

**Comment by marcussacana** [comment]
If it crashes to open the new font, then the bug is during the font regeneration,
not sure if is a bug or you did something wrong, but I'm not planning support this tool anymore.

**Comment by Real-Lolypops** [comment]
Got you, thanks anyway
