### ISSUE TITLE
Half-width draw help

### ISSUE THREAD

**Issue by Cosetto** [marcussacana/AquaPlusEditor#4]
Hey Marcus, I wonder can you also do the Half-width draw patch for [this game](https://store.steampowered.com/app/2432110/WHITE_ALBUM_Memories_like_Falling_Snow/) with the same engine too?
![image](https://github.com/marcussacana/AquaPlusEditor/assets/81801486/0eb7dd7a-77e4-404e-a032-c1dd2330054b)
Here's an example script like in the image.
[WA.zip](https://github.com/marcussacana/AquaPlusEditor/files/15096615/WA.zip)

**Comment by marcussacana** [comment]
Hi, I didn't looked in this game but since this is a PC game and utawarerumono is made for console, I expect for both engines be not the same, therefore will need a bit of analyze to do that and with my job is hard to had time to do that in now days, sorry.

**Comment by Cosetto** [comment]
Fyi, I did it somehow, following your Utawarerumono patch address to trace.
![image](https://github.com/marcussacana/AquaPlusEditor/assets/81801486/0021321d-bd55-4a2e-a26b-b834315d12cd)
![image](https://github.com/marcussacana/AquaPlusEditor/assets/81801486/0cc31c65-c278-424d-8d5f-67f1dfdd18fd)
